#!/usr/bin/env python3
"""
build_index.py — scans topics/**/*.html, extracts title + a text snippet,
writes topics/index.json and rewrites script.js with the data embedded.
Run this after adding/removing topic HTML files.
"""

import glob
import json
import os
import re
from html.parser import HTMLParser

HERE = os.path.dirname(os.path.abspath(__file__))
TOPICS_DIR = os.path.join(HERE, "topics")
OUTPUT_JSON = os.path.join(TOPICS_DIR, "index.json")
SCRIPT_JS = os.path.join(HERE, "script.js")


class TitleExtractor(HTMLParser):
    """Pull the <title> and first meaningful <p> as a snippet (skip <h1>/<title> for snippet)."""
    def __init__(self):
        super().__init__()
        self.title = ""
        self.snippet = ""
        self._capture_title = False
        self._capture_snippet = False
        self._snippet_chars = 0
        self._max_snippet = 400

    def handle_starttag(self, tag, attrs):
        if tag == "title":
            self._capture_title = True
        elif tag == "p" and not self.snippet:
            self._capture_snippet = True

    def handle_endtag(self, tag):
        if tag == "title":
            self._capture_title = False
        elif tag == "p" and self._capture_snippet:
            self._capture_snippet = False

    def handle_data(self, data):
        if self._capture_title:
            self.title = data.strip()
        elif self._capture_snippet and not self.snippet:
            text = data.strip()
            if text:
                cleaned = " ".join(text.split())
                self.snippet += (" " if self._snippet_chars else "") + cleaned
                self._snippet_chars += len(cleaned)
                if self._snippet_chars >= self._max_snippet:
                    self._capture_snippet = False


def extract_meta(html_path: str) -> dict:
    with open(html_path, "r", encoding="utf-8") as f:
        raw = f.read()
    parser = TitleExtractor()
    parser.feed(raw)

    # Fallback title from filename if <title> was empty
    title = parser.title or os.path.splitext(os.path.basename(html_path))[0].replace("-", " ").title()
    snippet = parser.snippet or "No description available."

    rel = os.path.relpath(html_path, HERE).replace("\\", "/")
    return {"title": title, "snippet": snippet, "path": rel}


def build():
    html_files = sorted(glob.glob(os.path.join(TOPICS_DIR, "**", "*.html"), recursive=True))
    # Exclude the index file itself if it ever lands in topics/
    html_files = [f for f in html_files if os.path.basename(f).lower() != "index.html"]

    topics = [extract_meta(f) for f in html_files]

    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(topics, f, indent=2, ensure_ascii=False)
    print(f"Wrote {OUTPUT_JSON} — {len(topics)} topics")

    # Rewrite script.js with the index embedded
    script = '// Auto-generated by build_index.py — do not edit manually.\n'
    script += 'const TOPICS_INDEX = ' + json.dumps(topics, ensure_ascii=False) + ';\n\n'
    script += generate_script()
    with open(SCRIPT_JS, "w", encoding="utf-8") as f:
        f.write(script)
    print(f"Wrote {SCRIPT_JS}")


def generate_script() -> str:
    return r'''
const topicsContainer = document.querySelector("#topics");
const topicCount = document.querySelector("#topic-count");
const searchInput = document.querySelector("#search-input");
const noResults = document.querySelector("#no-results");

function render(filter = "") {
  const q = filter.trim().toLowerCase();
  let visible = 0;

  // Clear previous
  topicsContainer.innerHTML = "";
  noResults.style.display = "none";

  if (!q) {
    // Show all
    TOPICS_INDEX.forEach((t) => {
      const card = document.createElement("a");
      card.href = t.path;
      card.className = "topic-card";
      card.innerHTML = `<span class="topic-title">${escapeHtml(t.title)}</span>`;
      topicsContainer.appendChild(card);
      visible++;
    });
  } else {
    TOPICS_INDEX.forEach((t) => {
      const titleMatch = t.title.toLowerCase().includes(q);
      const snippetMatch = t.snippet.toLowerCase().includes(q);
      if (titleMatch || snippetMatch) {
        const card = document.createElement("a");
        card.href = t.path;
        card.className = "topic-card search-hit";
        const matchLabel = titleMatch && snippetMatch ? "title + content" :
                           titleMatch ? "title" : "content";
        card.innerHTML = `
          <span class="topic-title">${escapeHtml(t.title)}</span>
          <span class="topic-match">matches ${matchLabel}</span>
        `;
        topicsContainer.appendChild(card);
        visible++;
      }
    });
  }

  topicCount.textContent = `${visible} ${visible === 1 ? "topic" : "topics"}`;

  if (visible === 0 && q) {
    noResults.style.display = "block";
    noResults.textContent = `No topics match "${escapeHtml(filter.trim())}"`;
  }
}

function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

// Initial render
render();

// Search: debounce + fuzzy substring match (title + snippet)
let debounceTimer;
if (searchInput) {
  searchInput.addEventListener("input", (e) => {
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => render(e.target.value), 120);
  });
}
'''


if __name__ == "__main__":
    build()
