// Auto-generated by build_index.py — do not edit manually.
const TOPICS_INDEX = [{"title": "Programming Concept Navigator", "snippet": "Encounter something → classify it → ask the right questions → understand the concept → then learn the syntax.", "path": "topics/programming-fundamentals/programming-fundamentals.html"}];


const topicsContainer = document.querySelector("#topics");
const topicCount = document.querySelector("#topic-count");
const searchInput = document.querySelector("#search-input");
const noResults = document.querySelector("#no-results");

function render(filter = "") {
  const q = filter.trim().toLowerCase();
  let visible = 0;

  // Clear previous
  topicsContainer.innerHTML = "";
  noResults.style.display = "none";

  if (!q) {
    // Show all
    TOPICS_INDEX.forEach((t) => {
      const card = document.createElement("a");
      card.href = t.path;
      card.className = "topic-card";
      card.innerHTML = `<span class="topic-title">${escapeHtml(t.title)}</span>`;
      topicsContainer.appendChild(card);
      visible++;
    });
  } else {
    TOPICS_INDEX.forEach((t) => {
      const titleMatch = t.title.toLowerCase().includes(q);
      const snippetMatch = t.snippet.toLowerCase().includes(q);
      if (titleMatch || snippetMatch) {
        const card = document.createElement("a");
        card.href = t.path;
        card.className = "topic-card search-hit";
        const matchLabel = titleMatch && snippetMatch ? "title + content" :
                           titleMatch ? "title" : "content";
        card.innerHTML = `
          <span class="topic-title">${escapeHtml(t.title)}</span>
          <span class="topic-match">matches ${matchLabel}</span>
        `;
        topicsContainer.appendChild(card);
        visible++;
      }
    });
  }

  topicCount.textContent = `${visible} ${visible === 1 ? "topic" : "topics"}`;

  if (visible === 0 && q) {
    noResults.style.display = "block";
    noResults.textContent = `No topics match "${escapeHtml(filter.trim())}"`;
  }
}

function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

// Initial render
render();

// Theme switcher — build after DOM is ready
const switcherEl = document.querySelector("#theme-switcher");
if (switcherEl) {
  buildSwitcher(switcherEl);
}

// Search: debounce + fuzzy substring match (title + snippet)
let debounceTimer;
if (searchInput) {
  searchInput.addEventListener("input", (e) => {
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => render(e.target.value), 120);
  });
}
